http:
  port: 8080

apiEndpoints:
  users:
    paths:
      - /users
      - /users/*

  posts:
    paths:
      - /posts
      - /posts/*

serviceEndpoints:
  userService:
    url: http://user-service:3001
  postService:
    url: http://post-service:3002

policies:
  - proxy

pipelines:
  users:
    apiEndpoints:
      - users
    policies:
      - proxy:
          - action:
              serviceEndpoint: userService

  posts:
    apiEndpoints:
      - posts
    policies:
      - proxy:
          - action:
              serviceEndpoint: postService
