name: CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js (for linting)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      # Install ESLint
      - name: Install ESLint
        run: npm install -g eslint

      # Run ESLint on all services

      - name: Run ESLint
        run: npx eslint . || echo "ESLint failed, but continuing..."

      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & Push User Service
      - name: Build and Push User Service
        uses: docker/build-push-action@v5
        with:
          context: ./user-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/user-service:latest

      # Build & Push Post Service
      - name: Build and Push Post Service
        uses: docker/build-push-action@v5
        with:
          context: ./post-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/post-service:latest

      # Build & Push Gateway
      - name: Build and Push Gateway
        uses: docker/build-push-action@v5
        with:
          context: ./blog-gateway
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gateway:latest
