name: Microservices CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ Install Dependencies and Run Lint (user-service)
      - name: Lint user-service
        working-directory: ./user-service
        run: |
          npm install
          npx eslint .

      # 4️⃣ Install Dependencies and Run Lint (post-service)
      - name: Lint post-service
        working-directory: ./post-service
        run: |
          npm install
          npx eslint .

      # 5️⃣ Lint Gateway
      - name: Lint gateway
        working-directory: ./blog-gateway
        run: |
          npm install
          npx eslint .

      # 6️⃣ Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # 7️⃣ Build Docker Images
      - name: Build Docker images
        run: docker compose build

      # 8️⃣ (Optional) Push Images to DockerHub
      - name: Login to DockerHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images
        if: github.ref == 'refs/heads/main'
        run: docker compose push
